const fs = require("fs");
const inquirer = require("inquirer");

inquirer
  .prompt([
    {
      type: "input",
      name: "title",
      message: "What is the title of your application?",
    },
    {
      type: "list",
      name: "license",
      message: "What license is your application using?",
      choices: ["Apache", "Boost", "BSD", "GNU LGPL v3", "None of the above"],
    },
    // {
    //   type: "input",
    //   name: "description",
    //   message: "Describe your application",
    // },
    // {
    //   type: "input",
    //   name: "installation",
    //   message: "Describe your application's installation process",
    // },
    // {
    //   type: "input",
    //   name: "usage",
    //   message: "Outline its usage information.",
    // },
    // {
    //   type: "input",
    //   name: "contribution",
    //   message: "Outline the contribution guidelines.",
    // },
    // {
    //   type: "input",
    //   name: "testing",
    //   message: "Detail testing information.",
    // },
    // {
    //   type: "input",
    //   name: "github",
    //   message: "What is your gitHub username?",
    // },
    // {
    //   type: "input",
    //   name: "email",
    //   message: "What is your email address?",
    // },
  ])
  .then((answers) => {
    fs.writeFile("generatedREADME.md", generateReadme(answers), (err) =>
      err ? console.log(err) : console.log("written successfully!")
    );
  });

const generateReadme = ({
  title,
  license,
  description,
  installation,
  usage,
  contribution,
  testing,
  github,
  email,
}) => {
  let notice;
  let badge;
  if (license === "Apache") {
    badge =
      "[![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)";
    notice = `- Apache Royale
      Copyright 2020 The Apache Software Foundation
    
    This product includes software developed at
    The Apache Software Foundation (http://www.apache.org/).
    
    The Initial Developer of some parts of the framework, which are copied from, derived from, or
    inspired by Adobe Flex (via Apache Flex), is Adobe Systems Incorporated (http://www.adobe.com/).
    Copyright 2003 - 2012 Adobe Systems Incorporated. All Rights Reserved.
    
    The Initial Developer of the examples/mxroyale/tourdeflexmodules,
    is Adobe Systems Incorporated (http://www.adobe.com/).
    Copyright 2009 - 2013 Adobe Systems Incorporated. All Rights Reserved.

  `;
  } else if (license === "Boost") {
    badge = `Apache Royale`;
    ("[![License](https://img.shields.io/badge/License-Boost_1.0-lightblue.svg)](https://www.boost.org/LICENSE_1_0.txt)");
    notice = `- Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:
    
    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.`;
  } else if (license === "BSD") {
    badge =
      "[![License](https://img.shields.io/badge/License-BSD_3--Clause-blue.svg)](https://opensource.org/licenses/BSD-3-Clause)";
    notice = `- BSD License 2010

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`;
  } else if (license === "GNU LGPL v3") {
    badge =
      "[![License: LGPL v3](https://img.shields.io/badge/License-LGPL_v3-blue.svg)](https://www.gnu.org/licenses/lgpl-3.0)";
    notice = `- GNU LGPL - Version 3.0

    This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
    
    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
    
    You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.`;
  } else (badge = ""), (notice = "Not licensed.");

  return `# ${title} ${badge}

  ---

  ## Description

  ${description}

  ## Table of contents

  1. [Installation Instructions](#installation)

  2. [Usage Information](#usage)

  3. [Contributions Guidelines](#contributions)

  4. [Testing](#testing)

  5. [License Information](#license)

  ---

  ## <a id="installation">Installation </a>

  ${installation}

  ## <a id="usage"> Usage </a>

  ${usage}

  ## <a id="contributions"> Contributions </a>

  ${contribution}

  ## <a id="testing">Testing</a>

  ${testing}

  ## <a id="license">License information</a>

  ${notice}

  This application is covered under ${license}.

  ## <a id= "questions"> Questions </a>

  For any additional questions, you can contact me:

  [${email}](https://${email})

  You can find my GitHub at:

  [${github}](https://${github})`;
};
// const licensing = () => {};
// licensing();
